import PDFDocument from "pdfkit";
import Groq from "groq-sdk";

const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY
});


// Remove markdown formatting
const cleanBold = (text) => {
    return text.replace(/\*\*(.*?)\*\*/g, "$1");
};


// Generate properly formatted PDF
const createFormattedPDF = (res, content, fileName) => {

    const doc = new PDFDocument({
        size: "A4",
        margin: 50,
        bufferPages: true
    });

    res.setHeader("Content-Type", "application/pdf");

    res.setHeader(
        "Content-Disposition",
        `attachment; filename="${fileName}"`
    );

    doc.pipe(res);


    // ---------- TITLE ----------
    doc
        .font("Helvetica-Bold")
        .fontSize(22)
        .text("AI Generated Document", {
            align: "center"
        });

    doc.moveDown(1);


    // ---------- CONTENT ----------
    const lines = content.split("\n");

    let insideCodeBlock = false;

    for (let line of lines) {

        line = line.trim();


        // Empty line
        if (!line) {
            doc.moveDown(0.5);
            continue;
        }


        // Code block start/end
        if (line.startsWith("```")) {

            insideCodeBlock = !insideCodeBlock;

            doc.moveDown(0.5);

            continue;
        }


        // Code block content
        if (insideCodeBlock) {

            doc
                .font("Courier")
                .fontSize(9)
                .text(line, {
                    indent: 10
                });

            continue;
        }


        // H1 - # Heading
        if (line.startsWith("# ")) {

            const heading = line
                .replace(/^# /, "")
                .replace(/\*\*/g, "");

            doc
                .moveDown(0.8)
                .font("Helvetica-Bold")
                .fontSize(18)
                .text(heading);

            doc.moveDown(0.3);

            continue;
        }


        // H2 - ## Heading
        if (line.startsWith("## ")) {

            const heading = line
                .replace(/^## /, "")
                .replace(/\*\*/g, "");

            doc
                .moveDown(0.6)
                .font("Helvetica-Bold")
                .fontSize(15)
                .text(heading);

            doc.moveDown(0.2);

            continue;
        }


        // H3 - ### Heading
        if (line.startsWith("### ")) {

            const heading = line
                .replace(/^### /, "")
                .replace(/\*\*/g, "");

            doc
                .moveDown(0.5)
                .font("Helvetica-Bold")
                .fontSize(13)
                .text(heading);

            doc.moveDown(0.2);

            continue;
        }


        // Bullet point
        if (
            line.startsWith("- ") ||
            line.startsWith("* ")
        ) {

            const bullet = line
                .replace(/^[-*]\s+/, "")
                .replace(/\*\*(.*?)\*\*/g, "$1");

            doc
                .font("Helvetica")
                .fontSize(11)
                .text(`• ${bullet}`, {
                    indent: 10,
                    width: 480
                });

            continue;
        }


        // Numbered list
        if (/^\d+\.\s/.test(line)) {

            const numbered = cleanBold(line);

            doc
                .font("Helvetica")
                .fontSize(11)
                .text(numbered, {
                    indent: 5,
                    width: 485
                });

            continue;
        }


        // Normal paragraph
        doc
            .font("Helvetica")
            .fontSize(11)
            .text(cleanBold(line), {
                align: "left",
                lineGap: 3
            });

    }


    // ---------- FOOTER ----------
    const range = doc.bufferedPageRange();

    for (
        let i = range.start;
        i < range.start + range.count;
        i++
    ) {

        doc.switchToPage(i);

        doc
            .font("Helvetica")
            .fontSize(8)
            .fillColor("gray")
            .text(
                `Generated by AI • Page ${i + 1} of ${range.count}`,
                50,
                780,
                {
                    align: "center",
                    width: 495
                }
            );
    }

    doc.end();
};



export const generatePDF = async (req, res) => {

    try {

        const { prompt } = req.body;


        // Validation
        if (!prompt || !prompt.trim()) {

            return res.status(400).json({
                success: false,
                message: "Prompt is required"
            });

        }


        // ---------- AI GENERATION ----------
        const response =
            await groq.chat.completions.create({

                model: "openai/gpt-oss-20b",

                messages: [

                    {
                        role: "system",

                        content: `
You are a professional document writer.

The user will give you a request for creating a document.

Create clean, professional and well-structured content.

IMPORTANT RULES:

1. Use Markdown headings:
# Main Title
## Section
### Subsection

2. Use bullet points with "-".

3. Use numbered lists when appropriate.

4. For programming code, use:
\`\`\`
code
\`\`\`

5. Keep paragraphs short and readable.

6. Do not add unnecessary explanations before or after the document.

7. Do not say "Here is your document".

8. Directly generate the final document content.

9. If the user asks for a resume, create an ATS-friendly professional resume.

10. If the user asks for programming/DSA content, preserve code blocks and explanations clearly.

11. Use professional English unless the user specifically asks for another language.
`
                    },

                    {
                        role: "user",
                        content: prompt.trim()
                    }

                ]

            });


        const content =
            response.choices?.[0]?.message?.content;


        if (!content) {

            return res.status(500).json({
                success: false,
                message: "AI failed to generate document content"
            });

        }


        // ---------- CREATE PDF ----------
        createFormattedPDF(
            res,
            content,
            "AI-Generated-Document.pdf"
        );


    } catch (error) {

        console.error(
            "PDF Generation Error:",
            error
        );


        if (!res.headersSent) {

            return res.status(500).json({
                success: false,
                message:
                    error.message ||
                    "Failed to generate PDF"
            });

        }

    }

};
